import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";

const CreateProjectSchema = z.object({
  name: z.string().min(1).max(200),
  project_type: z
    .enum([
      "residential",
      "commercial",
      "industrial",
      "institutional",
      "interior",
      "urban",
      "landscape",
      "other",
    ])
    .optional(),
  status: z
    .enum(["active", "on_hold", "completed"])
    .optional()
    .default("active"),
  budget_total: z.number().positive().optional(),
  design_budget: z.number().nonnegative().nullable().optional(),
  execution_budget: z.number().nonnegative().nullable().optional(),
  estimated_work_hours: z.number().int().positive().optional(),
  estimated_duration_days: z.number().int().positive().optional(),
  start_date: z.string().date().optional(),
  expected_end_date: z.string().date().optional(),
  site_location: z.string().max(500).optional(),
  site_lat: z.number().min(-90).max(90).optional(),
  site_lng: z.number().min(-180).max(180).optional(),
  site_geofence_radius_m: z.number().int().min(50).max(2000).optional(),
  drive_folder_url: z.string().url().optional().or(z.literal("")),
  customer_id: z.string().uuid().optional(),
  scope: z
    .enum(["design_only", "design_and_execution"])
    .optional()
    .default("design_and_execution"),
  apply_sal_preset: z.boolean().optional().default(true),
  apply_drawing_register: z.boolean().optional().default(true),
  table_preset_ids: z.array(z.string().uuid()).optional(),
  pipeline_template_ids: z.array(z.string().uuid()).optional(),
  payment_preset_id: z.string().uuid().nullable().optional(),
});

export async function GET(request: Request) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Bounded read: cap at 500 rows so the list never loads an unbounded set.
  // Optional ?page/?limit for explicit paging (matches the audit API convention).
  const { searchParams } = new URL(request.url);
  const page = Math.max(1, parseInt(searchParams.get("page") ?? "1"));
  const limit = Math.min(500, Math.max(1, parseInt(searchParams.get("limit") ?? "500")));
  const offset = (page - 1) * limit;

  const { data: projects, error, count } = await supabase
    .from("projects")
    .select(
      `
      id, name, slug, project_type, current_stage, status,
      budget_total, estimated_work_hours, estimated_duration_days,
      start_date, expected_end_date, actual_start_date, actual_end_date,
      site_location, drive_folder_url, is_placeholder,
      customer_portal_enabled, created_at,
      project_assignments ( user_id, role_on_project, contribution_pct,
        users!user_id ( full_name )
      ),
      project_checkpoints ( id, name, sequence_order, due_date, completed_at, requires_approval, approved_at )
    `,
      { count: "exact" }
    )
    .is("deleted_at", null)
    .order("created_at", { ascending: false })
    .range(offset, offset + limit - 1);

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ projects, meta: { total: count ?? 0, page, limit } });
}

export async function POST(request: Request) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: canCreate } = await supabase.rpc("has_capability", {
    p_capability: "project:create",
  });
  if (!canCreate) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const result = CreateProjectSchema.safeParse(body);
  if (!result.success) {
    return NextResponse.json(
      { error: result.error.issues[0]?.message ?? "Validation failed" },
      { status: 400 }
    );
  }

  const {
    apply_sal_preset,
    apply_drawing_register,
    table_preset_ids,
    pipeline_template_ids,
    payment_preset_id,
    drive_folder_url,
    customer_id,
    ...projectFields
  } = result.data;

  // Get caller's tenant_id via user_capabilities — simpler non-recursive RLS than users table
  const { data: cap, error: capError } = await supabase
    .from("user_capabilities")
    .select("tenant_id")
    .eq("user_id", user.id)
    .limit(1)
    .maybeSingle();

  if (!cap) {
    return NextResponse.json(
      { error: capError?.message ?? "User profile not found" },
      { status: 500 }
    );
  }

  const profile = { tenant_id: cap.tenant_id };

  // Insert project (slug auto-generated by trigger)
  const { data: project, error: insertError } = await supabase
    .from("projects")
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    .insert({ tenant_id: profile.tenant_id, created_by: user.id, updated_by: user.id, drive_folder_url: drive_folder_url || null, customer_id: customer_id ?? null, ...projectFields } as any)
    .select("id, name, slug, start_date")
    .single();

  if (insertError || !project) {
    return NextResponse.json(
      { error: insertError?.message ?? "Failed to create project" },
      { status: 500 }
    );
  }

  let pipelineTemplateIds = pipeline_template_ids ?? [];
  if (!pipeline_template_ids && apply_sal_preset) {
    const { data: template } = await supabase
      .from("checkpoint_templates")
      .select("id")
      .eq("tenant_id", profile.tenant_id)
      .eq("name", "Standard Architectural Lifecycle")
      .single();

    if (template) {
      pipelineTemplateIds = [template.id];
    }
  }

  for (const templateId of pipelineTemplateIds) {
      await supabase.rpc("apply_checkpoint_template", {
        p_project_id: project.id,
        p_template_id: templateId,
        p_start_date: projectFields.start_date ?? new Date().toISOString().split("T")[0],
      });
  }

  let tablePresetIds = table_preset_ids ?? [];
  if (!table_preset_ids && apply_drawing_register) {
    const { data: preset } = await supabase
      .from("table_presets")
      .select("id")
      .eq("tenant_id", profile.tenant_id)
      .eq("name", "Drawing Register")
      .single();

    if (preset) {
      tablePresetIds = [preset.id];
    }
  }

  for (const presetId of tablePresetIds) {
      await supabase.rpc("apply_table_preset", {
        p_project_id: project.id,
        p_preset_id: presetId,
        p_created_by: user.id,
      });
  }

  if (payment_preset_id) {
    const budget = Number(projectFields.budget_total ?? 0);
    if (budget > 0) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data: items } = await (supabase as any)
        .from("payment_milestone_preset_items")
        .select("milestone_name, percentage, sequence_order, notes")
        .eq("preset_id", payment_preset_id)
        .order("sequence_order");

      if (items && items.length > 0) {
        const today = new Date().toISOString().split("T")[0];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const rows = items.map((item: any) => ({
          project_id: project.id,
          milestone_name: item.milestone_name,
          amount_due: Math.round((Number(item.percentage) / 100) * budget * 100) / 100,
          due_date: today,
          sequence_order: item.sequence_order,
          notes: item.notes,
        }));

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await (supabase as any).from("payment_schedule").insert(rows);
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await (supabase as any)
          .from("projects")
          .update({ source_payment_preset_id: payment_preset_id })
          .eq("id", project.id);
      }
    }
  }

  return NextResponse.json({ project }, { status: 201 });
}
